CREATE TABLE `MSTBARANG` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `KODE` varchar(20) NOT NULL,
  `NAMA` varchar(100) NOT NULL,
  `JUMLAH_AWAL` int(10) NOT NULL,
  `HARGA_HPP` decimal(16,2) NOT NULL,
  `HARGA_JUAL` decimal(16,2) NOT NULL,
  `CREATED_DT` datetime NOT NULL,
  `UPDATE_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;
